name = "catppuccin-latte"
accent = "#1e66f5"
accent_subtle = "#a9c1f5"
fg = "#4c4f69"
fg_dim = "#8c8fa1"
fg_faint = "#ccd0da"
ok = "#40a02b"
warn = "#df8e1d"
danger = "#d20f39"
freeze = "#04a5e5"
bg_raised = "#e6e9ef"
bg = "#eff1f5"
